name: 'Github check run'
description: 'Wait a designated number of milliseconds'

inputs:
    github_token:
        description: 'number of milliseconds to wait'
        required: true

runs:
    using: 'node12'
    pre: 'dist/pre.js'
    main: 'dist/main.js'
    post: 'dist/post.js'
